  # Generated by Django 4.0.4 on 2022-05-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('uk', models.CharField(max_length=10)),
                ('chest', models.CharField(max_length=10)),
                ('waist', models.CharField(max_length=10)),
            ],
        ),
    ]
